version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: email-service-db
    environment:
      POSTGRES_USER: emailuser
      POSTGRES_PASSWORD: emailpass
      POSTGRES_DB: email_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - email-network

  # Redis for BullMQ Queue
  redis:
    image: redis:7-alpine
    container_name: email-service-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - email-network

  # Email Service API
  email-service:
    build: .
    container_name: email-service-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://emailuser:emailpass@postgres:5432/email_service"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: production
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - email-network

  # Bull Board (Queue Dashboard) - Atualizado para BullMQ
  bull-board:
    image: deadly0/bull-board
    container_name: email-service-dashboard
    ports:
      - "3001:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BULLMQ_ENABLED: "true"
    depends_on:
      - redis
    networks:
      - email-network

volumes:
  postgres_data:
  redis_data:

networks:
  email-network:
    driver: bridge